### ISSUE TITLE
Installation-Bug

### ISSUE THREAD

**Issue by RoundAboutWEB** [clonemeagain/osticket-slack#27]
System:  osTicket PLUS (v1.14.2 / Patch-3) — Deutsche Version
PHP-Version: 7.3.22
Error by Installation of Plugin:
```
[INSERT INTO ost_plugin SET installed=NOW() , install_path='plugins/osticket-slack-master', name='Slack notifier', isphar='', version=0.2]

Unknown column 'version' in 'field list'<br />
<br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #1054', '[INSERT INTO os...')<br />
#1 (root)/include/class.plugin.php(358): db_query('INSERT INTO ost...')<br />
#2 (root)/scp/plugins.php(51): PluginManager->install('plugins/osticke...')<br />
#3 {main}
```

**Comment by RoundAboutWEB** [comment]
The field "version" was missing in the table "ost_plugin". So now fixed.
